# Generated by Django 5.2.12 on 2026-03-31 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('entity_type', models.CharField(max_length=64, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(max_length=128, verbose_name='ID сущности')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='До')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='После')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудит',
                'verbose_name_plural': 'Аудит',
                'ordering': ['-created_at'],
            },
        ),
    ]
