# Generated by Django 5.2.12 on 2026-03-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('users_total', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('events_total', models.PositiveIntegerField(default=0)),
                ('button_clicks_total', models.PositiveIntegerField(default=0)),
                ('errors_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
    ]
