# Generated by Django 5.2.12 on 2026-03-31 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=512, verbose_name='Токен бота')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook secret')),
                ('base_url', models.URLField(default='https://platform-api.max.ru', verbose_name='Базовый URL')),
                ('webhook_path', models.CharField(default='/webhooks/max/', max_length=128, verbose_name='Путь webhook')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Бот включен')),
                ('debug_logging', models.BooleanField(default=False, verbose_name='Расширенное логирование')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_user_id', models.CharField(max_length=128, unique=True, verbose_name='Внешний ID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Первое взаимодействие')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последнее взаимодействие')),
                ('interactions_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во взаимодействий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='WebhookOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('set', 'Установить webhook'), ('update', 'Обновить webhook'), ('info', 'Получить информацию'), ('delete', 'Удалить webhook'), ('check', 'Проверка соединения')], max_length=16, verbose_name='Операция')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Запрос')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Ответ')),
                ('status', models.CharField(max_length=32, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Операция webhook',
                'verbose_name_plural': 'Операции webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название кнопки')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('node_type', models.CharField(choices=[('menu', 'Меню'), ('message', 'Сообщение'), ('link', 'Ссылка'), ('back', 'Назад'), ('root', 'В главное меню'), ('action', 'Заглушка под действие'), ('transition', 'Служебный переход')], default='menu', max_length=32, verbose_name='Тип узла')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать кнопку')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Служебный payload')),
                ('icon', models.CharField(blank=True, max_length=16, verbose_name='Иконка/эмодзи')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='bot.menunode')),
            ],
            options={
                'verbose_name': 'Узел меню',
                'verbose_name_plural': 'Узлы меню',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=list, verbose_name='История')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='bot.menunode')),
                ('previous_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_sessions', to='bot.menunode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Состояние сессии',
                'verbose_name_plural': 'Состояния сессий',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID события')),
                ('event_type', models.CharField(max_length=80, verbose_name='Тип события')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('processed', 'Обработано'), ('failed', 'Ошибка'), ('duplicate', 'Дубликат'), ('rejected', 'Отклонено')], default='received', max_length=16, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность, мс')),
                ('related_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.menunode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Webhook-событие',
                'verbose_name_plural': 'Webhook-события',
                'ordering': ['-received_at'],
            },
        ),
    ]
