# Generated by Django 5.2.12 on 2026-04-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionstate',
            name='last_bot_message_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID последнего сообщения бота'),
        ),
    ]
