# Generated by Django 5.2.12 on 2026-04-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_usersessionstate_last_bot_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersessionstate",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="ID чата"),
        ),
    ]
